cargo-features = ["edition2024"]
[package]
name = "ron-assista-bot"
version = "2.1.2"
edition = "2024"

[dependencies]
chrono = "0.4.38"
once_cell = "1.19.0"
poise = { version = "0.6.1" }
regex = "1.10.4"
reqwest = { version = "0.12.4" }
roboat = "0.35.0"
serde_json = "1.0.120"
serenity = { version = "0.12.1", features = ["rustls_backend"], default-features = false }
static-toml = "1.2.0"
tokio = "1.37.0"
